image: python:3.9

stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - pip install -U pip
    - pip install mkdocs
    - pip install mkdocs-material
  script:
    - mkdocs build -d public
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - echo 'Skip script section' 
  artifacts:
    paths:
      - public
  only:
    - main

